### PR TITLE
Update Bootstrap to 4.1.0 + Update FontAwesome to 5.0.12

### PR DESCRIPTION
**Pull request by theshaun**
I suspect this will need a bit more testing, but I have been using this Bootstrap template at work and looking at using it for some side projects.

I have done the following:

- Update FontAwesome to 5.0.12
- Remove deprecated .text-hide mixin scenario
- Update some npm packages
- Fix up usage of FontAwesome fonts across all pug and scss files

If something doesn't seem right, let me know and I can look at fixing any issues from the upgrade

### CODE REVIEW

**Comment by theshaun** [comment]
Just realised I forgot to include the update bootstrap JS files, I'll add those to my branch and update this pull request.

**Comment by theshaun** [comment]
amended with updated Bootstrap JS file

**Comment by pratikborsadiya** [comment]
Hi Shaun,

I myself have updated the bootstrap version to 4.1.1 and I am about to release a new version of the theme v.2.4.0. So I am sorry to tell you that I cannot merge Bootstrap version upgrade 4.1.0 but I would surely like to merge the FontAwesome upgrade in upcoming 2.4.0 release. if you can update the pull request to only include FontAwesome version update or create a new pull request for the same, I will include those changes in the main repository. 

Thank you for the contribution.

**Comment by theshaun** [comment]
Hey, 

More than happy to take a look at putting together a pull requiest with just the FontAwesome changes.

They are part in scss and also the pug files. I'm not sure what ammendments you have made to either for your 2.4.0 release. If you have another branch with this code in it I could take a look and merge in my changes to that.

**Comment by pratikborsadiya** [comment]
I have just pushed a branch v2.4.0. you can use that branch as base for your pull request. Later on I will merge the branch into master when releasing v2.4.0.

**Comment by theshaun** [comment]
All good, will look at that branch and see how I go. I'll close this pull request

**Pull request closed without merging**
